### ISSUE TITLE
Intermediate States

### ISSUE THREAD

**Issue by ankuj** [KCL-Planning/VAL#14]
Hello,

Is there a means to capture intermediate state information between actions by means of the validator?

Thanks
Ankuj

**Comment by DerekLong101** [comment]
There are at least a couple of ways to get information, but they do depend on some extra code that exists outside the archive. I can supply it to you, but I need to know what you want to do with it and whether what I have is suitable.

Cheers

Derek



Sent from Samsung tablet


-------- Original message --------

**Comment by ankuj** [comment]
Hello @DerekLong101 , thanks for the answer. I am actually developing an algorithm to learn action models from action sequences, and am trying to measure how much the injection of state information improves the learning achieved. I would appreciate if there could be a way I could collect action-state-action sequences from the code.  I would gladly cite the VAL system for the same as well :)
Thanks

**Comment by DerekLong101** [comment]
OK. Give me a few days to sort out the code archive, but I think I can deliver.


Cheers


Derek

________________________________

**Comment by ankuj** [comment]
Thanks that would be very kind of you :)

**Comment by jan-dolejsi** [comment]
This is now being released as the ValStep utility.
