### ISSUE TITLE
Plan accepted while it should not

### ISSUE THREAD

**Issue by mabdula** [KCL-Planning/VAL#27]
Attached is a zip file containing a domain (domain_2.pddl) , an instance (inst_2.pddl) and an incorrect plan (plan_2.pddl). Running the "validate" executable on the three files gives the following output:

Checking plan: plan_2.pddl
Plan executed successfully - checking goal
Plan valid
Final value: 1 

Successful plans:
Value: 1
 plan_2.pddl 1

[bug2.zip](https://github.com/KCL-Planning/VAL/files/2066109/bug2.zip)

Cheers,
Mohammad

**Comment by DerekLong101** [comment]
This one, on the other hand, is a significant problem. A long-lived bug has been uncovered! There is a (flawed) assumption deep in the machinery for tracking literals (and functions) that the concatenation of the strings that make up their names, together with the names of their grounded arguments, will uniquely identify them - not true if you have (P O AOB ) and (P OA OB ). This has now been corrected in my code base and I will push it to the repository as soon as I have access to it.


Cheers


Derek

________________________________

**Comment by jan-dolejsi** [comment]
This appears to be fixed in the latest codebase (about to be pushed to the repo). When the PR is accepted, this issue should be closed.

```
Plan to validate:

Plan size: 1
1:
(a1 oa ob)
 

Plan Validation details
-----------------------

Checking next happening (time 1)
Plan failed because of unsatisfied precondition in:
(a1 oa ob)

Plan failed to execute

Plan Repair Advice:

(a1 oa ob) has an unsatisfied precondition at time 1
(Set (p1 oa ob) to true)


Failed plans:
...plan_2.pddl 

Exit code: 1
```
