### ISSUE TITLE
Use part of VAL in open source project not under LGPL license

### ISSUE THREAD

**Issue by fteicht** [KCL-Planning/VAL#37]
Dear VAL developers,

I would like to reuse VAL's PDDL+ parser in a future open-source project aiming at modelling and solving RL/planning/scheduling problems. This project will not be under the LGPL license but MIT or BSD-like. I do not intend to modify your PDDL parser source code but rather to ship it in a separate sdk directory. Also, I would like to provide only the source of the parser instead of the full VAL repository because, for instance, I do not need the compiled binaries you provide in the repository.

Would you allow me to do that?

Thank you very much in advance!
Kind regards,
Florent

**Comment by DerekLong101** [comment]
Hi Florent


As it happens, I am currently involved in a project to port all the VAL source to a new repository with a BSD license. I have permission for this from the original contributors and plan to consult with more recent contributors to confirm that they are happy to allow their contributions to be ported into the new repository. However, I have to also request permission from the (technical) IP owner (the University) and this is in progress - in fact I have a call to explore this tomorrow. Therefore, I hope to be able to provide you with a definitive response very shortly.


Cheers


Derek

________________________________

**Comment by fteicht** [comment]
That would be excellent!
Thank you for your quick answer and support. I hope your effort to port the library to the BSD license will succeed, it will significantly help the community build upon your library.
Cheers,
Florent

**Comment by DerekLong101** [comment]
Hi Florent


Just to keep you updated - the discussions were helpful, but incomplete. I am also discussing things with Strathclyde, who actually technically own the IP for most of the work (although Durham is also involved and I need to contact them, too). I'll keep you updated as things move forward - I really hope to have a useful conclusion shortly.


- Derek

________________________________

**Comment by jan-dolejsi** [comment]
FYI, the change of license was agreed by all the involved parties and the Pull Request is coming very soon.

**Comment by jan-dolejsi** [comment]
FYI, we are taking a little bit longer to set the continuous integration right and to ensure the binaries work on Linux and MacOS without having to set the library path.
