### ISSUE TITLE
VAL fails to validate temporal plan

### ISSUE THREAD

**Issue by poojakashyap121** [KCL-Planning/VAL#39]
Hi, 
I have an issue with VAL validating a plan generated from popf.
Below are the attached files with the plan created by popf, and the domain and problem files. The plan generated (from popf) is 'rover-plan.pddl', and then validated with VAL.
VAL gives an error about unsatisfied preconditions, which does not sound right. This is in the VAL output file.

Help appreciated. Thanks!
[KCLRover.zip](https://github.com/KCL-Planning/VAL/files/3442183/KCLRover.zip)

**Comment by jan-dolejsi** [comment]
The latest VAL validates this plan correctly. Did you specify the ` -t 0.001` epsilon? Popf uses that value, while VAL defaults to `0.01`.

```
Checking plan: [...]rover-plan.pdd
Plan executed successfully - checking goal
Plan valid
Final value: 109.618

Successful plans:
Value: 109.618
[...]rover-plan.pdd 109.618
```

Please confirm, so we can close the issue.

**Comment by poojakashyap121** [comment]
Hey, Thanks!
