### ISSUE TITLE
Restore support for sequential plans

### ISSUE THREAD

**Issue by jendrikseipp** [KCL-Planning/VAL#46]
The new VAL requires plans to have timestamps. It would be great if VAL also accepted sequential plans, i.e., plans without timestamps.

**Comment by DerekLong101** [comment]
That's weird - it was not intended to be a deprecated feature. I will check.

**Comment by silvansievers** [comment]
Any chance you can look into this soonish, given the recent activity? :) We would really like to use the latest VAL (which builds easily under Windows, I suppose), to validate classical plans of Fast Downward on Windows.

**Comment by guicho271828** [comment]
Is it not checked by Azure pipeline? If not, it is better to have unit tests performed in it

**Comment by DerekLong101** [comment]
I have started to look at this - I planned to finish it this week, but something has come up and it will now be a few more days - start of next week.

**Comment by DerekLong101** [comment]
Finally had the chance to finish this one off.

**Comment by jendrikseipp** [comment]
That's great, thanks a lot!
