### ISSUE TITLE
?after is not an accepted variable name

### ISSUE THREAD

**Issue by silvansievers** [KCL-Planning/VAL#48]
The domain data-network from last IPC (IPC 2018) is rejected with "Problem in domain definition". After lots of debugging, I figured out that the problem is that ?after seems not to be a valid variable name. I can only assume that "after" has a special meaning in other contexts, but nevertheless, this domain file should be accepted as valid PDDL in my opinion.
[data-network-domain.tar.gz](https://github.com/KCL-Planning/VAL/files/4936642/data-network-domain.tar.gz)

**Comment by DerekLong101** [comment]
Thanks for this observation - you are right that "after" has been adopted as a keyword in the language, but unofficially, and it really should not prevent the use in this context. I will fix it.

**Comment by DerekLong101** [comment]
This one should be fixed, now.

**Comment by roeger** [comment]
Hi @DerekLong101  and all,

we just tested this because we wanted to update the Fast Downward build instructions to use a more recent version of VAL. We still observe the issue, also when building from scratch from the tip.

**Comment by DerekLong101** [comment]
It's true, "after" is a keyword in the PDDL dialect VAL supports. I need to take a look at the parser, I guess, to see whether I can easily avoid the lexer returning a token when the context wants a string.

Cheers

Derek
________________________________
