### ISSUE TITLE
How to use TIM ?

### ISSUE THREAD

**Issue by aymeric75** [KCL-Planning/VAL#57]
Hello,

I just built the VAL project (using VAL/scripts/linux/build_linux64.sh all Release)

Now I would like to use TIM, I have a domain.pddl (and a problem.pddl) file.

I tried 

`./TIM < output.sas`  (sas file generated by fastdownward)

But I get:

**Segmentation fault (core dumped)**

Thank you

**Comment by DerekLong101** [comment]
TIM doesn't take sas files as input - none of the VAL tools do. It takes pddl files, using the same parser as all of the tool suite.
________________________________
From: aymeric75 ***@***.***>
Sent: 18 October 2022 15:48
To: KCL-Planning/VAL ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [KCL-Planning/VAL] How to use TIM ? (Issue #57)


Hello,

I just built the VAL project (using VAL/scripts/linux/build_linux64.sh all Release)

Now I would like to use TIM, I have a domain.pddl (and a problem.pddl) file.

I tried

./TIM < output.sas (sas file generated by fastdownward)

But I get:

Segmentation fault (core dumped)

Thank you

**Comment by DerekLong101** [comment]
Oh, furthermore, all of the tools use command line arguments, not piped input.
________________________________

**Comment by aymeric75** [comment]
Ok, indeed, thanks, other probs came, I m going to open a new issue. Regards
