### ISSUE TITLE
parser error leads to crash

### ISSUE THREAD

**Issue by maltehelmert** [KCL-Planning/VAL#6]
I tried to validate a plan for and example problem encoding a 15-puzzle instance and got a segmentation fault. I think the issue was the name of the problem in the "header" of the problem file. With my original `(define (problem 15-puzzle-example) ...` I got a segfault. Changing it to `(define (problem fifteen-puzzle-example) ...` fixed it, so I assume leading digits in tokens aren't allowed.

The allowed tokens may even be documented somewhere, I didn't check and went with the "almost anything goes" attitude of LISP. :-) But it would be nice if the crash would be less hard and led to an error message that could help debug the failing PDDL. (It worked with Fast Downward. Trying FF gave an error message that pointed me towards this token.)

I can provide example inputs if necessary, but this can probably be reproduced by changing the `problem` bit in an arbitrary input file.

**Comment by DerekLong101** [comment]
Fixed this now!
