### ISSUE TITLE
Segfault during plan repair

### ISSUE THREAD

**Issue by flogo** [KCL-Planning/VAL#8]
When calling `validate -e domain.pddl problem.pddl sas_plan.invalid` with the attached files, the process ends with a segmentation fault during the plan repair step.

Domain: http://pastebin.com/eMWN1xDk (blocks)
Problem: http://pastebin.com/3Mfn15Lc (probBLOCKS-4-0.pddl)
Invalid plan: http://pastebin.com/aKWamXYb

Debugging with gdb shows the error in line 2957 of `Validator.cpp`:

```
Program received signal SIGSEGV, Segmentation fault.
0x00000000004973f9 in VAL::PlanRepair::slideEndOfPlan (this=0x7fffffffcc90, repairingPlan=0x7c73b0, firstAction=0x7c1f20) at src/Validator.cpp:2957
2957                              metric,stepLength,durative,current_analysis->the_domain->constraints,current_analysis->the_problem->constraints);
```

**Comment by DerekLong101** [comment]
Thanks flogo. I will look into this as soon as I get a chance. The plan repair machinery has not been worked on for quite a while and I think it is fair to say it is not as robust as the validation itself. Still, it is good to get bug reports so we can try to fix it!

**Comment by flogo** [comment]
Thanks. This is not urgent, I just wanted to let you know. I'm currently using a hacked version as a workaround which just disables the plan repair (I was interested in the reason for failure, not the advice on how to repair it, but I didn't find an option to enable just one of those.)

**Comment by DerekLong101** [comment]
I have had a look at the problem and plan and it is clear that this is not a plan that can be fixed by easy modifications. The plan repair machinery makes assumptions about what kind of problems might be being faced and those assumptions are not valid here. Clearly, VAL should report that it cannot fix the plan rather than crashing, but VAL is not a planner, so it cannot repair this. 

If you want to understand what is wrong with the plan, use the -v flag - it will point out that the 3rd action is not possible because c is not clear.

**Comment by DerekLong101** [comment]
Ah. I think you want to use the -v flag and not the -e flag (-e was really an experimental option for a project some time ago).

**Comment by flogo** [comment]
I see, thanks. The -v option was a bit to verbose for my taste, I prefer to show the error reason without the log. I'm currently working with Christian Muise on including VAL in his planning.domains framework. I guess we could also switch to the -v option but currently using the -e option and commenting out the plan repair step generates just the output I wanted.

Cheers,
Florian

**Comment by DerekLong101** [comment]
I will treat this as a feature request if a specific request if made.
